#!/usr/bin/env bash
# Time-stamp: 2024-06-01T12:00:00Z

# this is a backup script that uses restic to backup files from multiple machines.
# The script reads a YAML configuration file that specifies the machines,
# the paths to include and exclude for each machine. The script then uses restic
# to perform the backup and applies retention policies.

set -eEuo pipefail
export PATH='/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin'

# set to non-zero to enable dry-run mode
declare -r DRY_RUN=0

declare -a OPTIONS=()
(( DRY_RUN )) && OPTIONS+=('--dry-run')

## functions
##
# parse the YAML config from this script, starting after the line that begins with "end_of_script="
gen-yaml(){
    awk -v end="'" '/^end_of_script=/ {p=1; next} p && $0 != end' < "$0"
}

gen-exclude-list(){
    declare machine_name="$1"
    # shellcheck disable=SC2016
    gen-yaml | yq --raw-output --arg mn "$machine_name" \
       '.machines[] | select(.machine_name == $mn) | .exclude_paths[]'
}

gen-include-list(){
    declare machine_name="$1"
    # shellcheck disable=SC2016
    gen-yaml | yq --raw-output --arg mn "$machine_name" \
       '.machines[] | select(.machine_name == $mn) | .include_paths[]'
}

check_vars_are_set(){
    declare -a vars=(AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
                     RESTIC_REPOSITORY RESTIC_PASSWORD_FILE)
    declare -a unset_vars=()
    for var in "${vars[@]}"; do
        if [[ -z "${!var:-}" ]]; then
            unset_vars+=("$var")
        fi
    done
    if ((${#unset_vars[@]})); then
        echo "The following required variables are not set:" >&2
        printf '  %s\n' "${unset_vars[@]}" >&2
        exit 1
    fi
} # check_vars_are_set()

# pre-flight check
if yq --help 2>&1 | grep -q '/kislyuk/yq'
then
    echo "yq is the correct (Python) version."
else
    echo "yq is not the correct version. Please install the Python version of yq from Andrey Kislyuk."
    exit 1
fi

declare THIS_HOST
declare -i THIS_HOST_FOUND=0
THIS_HOST="$(hostname -s)"
readonly THIS_HOST
while IFS= read -r mn
do
    if [[ "${THIS_HOST}" == "$mn" ]]; then
       THIS_HOST_FOUND=1
    fi
done < <(gen-yaml  | yq -r '.machines[].machine_name')

if ((!THIS_HOST_FOUND))
then
    echo "Host ${THIS_HOST} not found." >&2
    exit 1
fi

if [[ ! -v CREDENTIALS_DIRECTORY ]]; then
    echo "CREDENTIALS_DIRECTORY is not set, checking fallback variables." >&2
    check_vars_are_set
else
        AWS_ACCESS_KEY_ID="$(<"${CREDENTIALS_DIRECTORY}/aws_access_key_id")"
        AWS_SECRET_ACCESS_KEY="$(<"${CREDENTIALS_DIRECTORY}/aws_secret_access_key")"
        # Check if restic_repository file exists, if not, construct RESTIC_REPOSITORY from bucket and hostname
        if [[ -e "${CREDENTIALS_DIRECTORY}/restic_repository" ]]; then
            RESTIC_REPOSITORY="s3:$(<"${CREDENTIALS_DIRECTORY}/restic_repository")"
        else
            RESTIC_REPOSITORY="s3:$(<"${CREDENTIALS_DIRECTORY}/restic_repository_bucket")/${THIS_HOST}"
        fi
        RESTIC_PASSWORD_FILE="${CREDENTIALS_DIRECTORY}/restic_password"
fi
export AWS_DEFAULT_REGION=auto
export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
export RESTIC_REPOSITORY RESTIC_PASSWORD_FILE

if restic cat config &>/dev/null; then
  echo "Restic repository already initialized."
else
  echo "Initializing restic repository..."
  restic init
fi

# restic unlock && restic prune && restic check && exit
# Backup script
restic backup --files-from <(gen-include-list "$THIS_HOST") \
  --exclude-file <(gen-exclude-list "$THIS_HOST") \
  --tag daily "${OPTIONS[@]}"

# Retention
restic forget --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --prune


# data below after end_of_script (must end in solitary single quote)
# shellcheck disable=SC2034
end_of_script='
machines:
  - machine_name: srv1
    include_paths:
      - "/home/allan/Documents/"
      - "/home/allan/workarea/"
      - "/etc/"
    exclude_paths:
      - "*.log"
      - "/home/allan/workarea/github/**"
      - "/home/allan/workarea/Users/**"

  - machine_name: srv2
    include_paths:
      - "/afs"
      - "/bin"
      - "/boot"
      - "/dev"
      - "/etc"
      - "/grub2"
      - "/home"
      - "/lib"
      - "/lib64"
      - "/media"
      - "/mnt"
      - "/opt"
      - "/root"
      - "/sbin"
      - "/srv"
      - "/tmp"
      - "/usr"
      - "/var"
    exclude_paths:
      - "/media/**"
      - "/mnt/**"
      - "/tmp/"
      - "/var/cache/"
      - "/var/log/"
      - "/var/media/"
      - "/var/spool/"
      - "/var/swap/"
      - "/var/tmp/"

  - machine_name: srv3
    include_paths:
      - "/bin"
      - "/boot"
      - "/etc"
      - "/home"
      - "/initrd*"
      - "/lib"
      - "/lib64"
      - "/opt"
      - "/root"
      - "/sbin"
      - "/srv"
      - "/usr"
      - "/var"
      - "/vmlinu*"
    exclude_paths:
      - "/proc/**"
      - "/sys/**"
      - "/run/**"
      - "/tmp/**"
      - "/var/cache/**"
      - "/var/tmp/**"
      - "/var/spool/**"

  - machine_name: srv4
    include_paths:
      - "/altroot/"
      - "/bsd*"
      - "/bin/"
      - "/etc/"
      - "/home/"
      - "/root/"
      - "/sbin"
      - "/usr/"
      - "/var/"
    exclude_paths:
      - "/lost+found/"
      - "/tmp/"
      - "/var/cache/**"
      - "/var/log/**"
      - "/var/run/**"
      - "/var/spool/**"
      - "/var/tmp/**"
'
