#!/bin/bash
# Time-stamp: 2024-06-01T12:00:00Z

# this is a backup script that uses restic to backup files from multiple machines.
# The script reads a YAML configuration file that specifies the machines,
# the paths to include and exclude for each machine. The script then uses restic
# to perform the backup and applies retention policies.

set -eEuo pipefail

# set to non-zero to enable dry-run mode
declare -r DRY_RUN=1

declare -a OPTIONS=()
(( DRY_RUN )) && OPTIONS+=('--dry-run')

gen-yaml(){
    awk -v end="'" '/^end_of_script=/ {p=1; next} p && $0 != end' < "$0"
}

gen-exclude-list(){
    declare machine_name="$1"
    # shellcheck disable=SC2016
    gen-yaml | yq --raw-output --arg mn "$machine_name" \
       '.machines[] | select(.machine_name == $mn) | .exclude_paths[]'
}

gen-include-list(){
    declare machine_name="$1"
    # shellcheck disable=SC2016
    gen-yaml | yq --raw-output --arg mn "$machine_name" \
       '.machines[] | select(.machine_name == $mn) | .include_paths[]'
}

declare THIS_HOST
declare -i THIS_HOST_FOUND=0
THIS_HOST="$(hostname -s)"
readonly THIS_HOST
while IFS= read -r mn
do
    if [[ "${THIS_HOST}" == "$mn" ]]; then
       THIS_HOST_FOUND=1
    fi
done < <(gen-yaml  | yq -r '.machines[].machine_name')

if ((!THIS_HOST_FOUND))
then
    echo "Host ${THIS_HOST} not found." >&2
    exit 1
fi

check_vars_are_set(){
    declare -a vars=(AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
                     RESTIC_REPOSITORY RESTIC_PASSWORD_FILE)
    declare -a unset_vars=()
    for var in "${vars[@]}"; do
        if [[ -z "${!var:-}" ]]; then
            unset_vars+=("$var")
        fi
    done
    if ((${#unset_vars[@]})); then
        echo "The following required variables are not set:" >&2
        printf '  %s\n' "${unset_vars[@]}" >&2
        exit 1
    fi
} # check_vars_are_set()

if [[ ! -v CREDENTIALS_DIRECTORY ]]; then
    echo "CREDENTIALS_DIRECTORY is not set, checking fallback variables." >&2
    check_vars_are_set
else
        AWS_ACCESS_KEY_ID="$(<"${CREDENTIALS_DIRECTORY}/aws_access_key_id")"
        AWS_SECRET_ACCESS_KEY="$(<"${CREDENTIALS_DIRECTORY}/aws_secret_access_key")"
        # Check if restic_repository file exists, if not, construct RESTIC_REPOSITORY from bucket and hostname
        if [[ -e "${CREDENTIALS_DIRECTORY}/restic_repository" ]]; then
            RESTIC_REPOSITORY="s3:$(<"${CREDENTIALS_DIRECTORY}/restic_repository")"
        else
            RESTIC_REPOSITORY="s3:$(<"${CREDENTIALS_DIRECTORY}/restic_repository_bucket")/${THIS_HOST}"
        fi
        RESTIC_PASSWORD_FILE="${CREDENTIALS_DIRECTORY}/restic_password"
fi
export AWS_DEFAULT_REGION=auto
export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
export RESTIC_REPOSITORY RESTIC_PASSWORD_FILE

if restic cat config &>/dev/null; then
  echo "Restic repository already initialized."
else
  echo "Initializing restic repository..."
  restic init
fi

# restic unlock && restic prune && restic check && exit
# Backup script
restic backup --files-from <(gen-include-list "$THIS_HOST") \
  --exclude-file <(gen-exclude-list "$THIS_HOST") \
  --tag daily "${OPTIONS[@]}"

# Retention
restic forget --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --prune


# data below after end_of_script (must end in solitary single quote)
# shellcheck disable=SC2034
end_of_script='
machines:
  - machine_name: web01
    include_paths:
      - "/home/joe/Documents/"
      - "/home/joe/workarea/"
      - "/etc/"
    exclude_paths:
      - "*.log"
      - "/home/joe/workarea/github/**"
      - "/home/joe/workarea/Users/**"

  - machine_name: web02
    include_paths:
      - /var/lib/mysql
      - /etc/mysql
      - /backup/scripts
    exclude_paths:
      - /var/lib/mysql/tmp
      - /var/lib/mysql/binlogs
      - /backup/scripts/archive

  - machine_name: db01
    include_paths:
      - /opt/application
      - /etc/systemd/system
      - /home/deploy
    exclude_paths:
      - /opt/application/logs
      - /opt/application/cache
      - /home/deploy/.cache

  - machine_name: bsd01
    include_paths:
      - "/altroot/"
      - "/bsd*"
      - "/bin/"
      - "/etc/"
      - "/home/"
      - "/root/"
      - "/sbin"
      - "/usr/"
      - "/var/"
    exclude_paths:
      - "/lost+found/"
      - "/tmp/"
'
